package application.controller;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import application.Main;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.CheckBox;

public class FindwordController {
	@FXML
	private Button btn_find;
	@FXML
	private Button btn_quit;
	@FXML
	private TextField tf_code;
	@FXML
	private TextField tf_phone;
	@FXML
	private CheckBox cb_manage;
	
//	Main m;

	// Event Listener on Button[#btn_find].onMouseClicked
	@FXML
	public void find_password(MouseEvent event) {
		// TODO Autogenerated
		if (tf_code==null || tf_code.getText() == null) {
			JOptionPane.showMessageDialog(null, "编号不能为空", "提示", 0);
			return;
		}
		if (tf_phone==null || tf_phone.getText() == null) {
			JOptionPane.showMessageDialog(null, "手机号不能为空", "提示", 0);
			return;
		}
		String phone = tf_phone.getText(), password = "null";
		int acount = Integer.parseInt(tf_code.getText());
		PreparedStatement psmt;
		ResultSet rs;
		if(!cb_manage.isSelected()) { // 读者
			try {
				String sql = "select * from dbo.Reader where Rno = ? and Rphone = ?";
				psmt = Main.con.prepareStatement(sql);
				psmt.setInt(1, acount);
				psmt.setString(2, phone);
				// 执行SQL语句
				rs = psmt.executeQuery();

				while (rs.next()) {
					password = rs.getString("Rpassword");
				}
				if(password.equals("null")) {
					quit(null);
					JOptionPane.showMessageDialog(null, "编号或者手机号码错误!无法找到密码!", "消息提示", 0);
				}
				else {
					quit(null);
					JOptionPane.showMessageDialog(null, "密码找回:" + password, "消息提示", 1);
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		else {
			//管理员
			try {
				String sql = "select * from dbo.Manager where Mcode = ? and Mphone = ?";
				psmt = Main.con.prepareStatement(sql);
				psmt.setString(1, tf_code.getText());
				psmt.setString(2, phone);
				// 执行SQL语句
				rs = psmt.executeQuery();

				while (rs.next()) {
					password = rs.getString("Mpassword");
				}
				if(password.equals("null")) {
					quit(null);
					JOptionPane.showMessageDialog(null, "编号或者手机号码错误!无法找到密码!", "消息提示", 0);
				}
				else {
					quit(null);
					JOptionPane.showMessageDialog(null, "密码找回:" + password, "消息提示", 1);
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
	}
	// Event Listener on Button[#btn_quit].onMouseClicked
	@FXML
	public void quit(MouseEvent event) {
		// TODO Autogenerated
		Main.findstage.close();
	}
	
//	public void setMain(Main m) {
//		this.m = m;
//	}
}
