package application.controller;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import application.Main;
import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

public class NewBookController {
	@FXML
	private TextField tf_name;
	@FXML
	private TextField tf_auther;
	@FXML
	private TextField tf_price;
	@FXML
	private TextField tf_type;
	@FXML
	private TextField tf_des;
	
	private ManagerViewController mc;
	
	public void setMC(ManagerViewController mc) {
		this.mc = mc;
	}

	// Event Listener on Button.onMouseClicked
	@FXML
	public void addBook(MouseEvent event) {
		// TODO Autogenerated
		if(tf_name == null || tf_name.getText() == null) {
			JOptionPane.showMessageDialog(null, "书名不为空!", "错误", 0);
			return;
		}
		if(tf_auther == null || tf_auther.getText() == null) {
			JOptionPane.showMessageDialog(null, "作者不为空!", "错误", 0);
			return;
		}
		if(tf_price == null || tf_price.getText() == null) {
			JOptionPane.showMessageDialog(null, "书的价格不为空!", "错误", 0);
			return;
		}
		if(tf_type == null || tf_type.getText() == null) {
			JOptionPane.showMessageDialog(null, "书的类型不为空!", "错误", 0);
			return;
		}
		if(tf_des == null || tf_des.getText() == null) {
			JOptionPane.showMessageDialog(null, "请描述一下这个本书!", "错误", 0);
			return;
		}
		
		String sql;
		PreparedStatement psmt;
		ResultSet rs;
		try {
			sql = "select count(*) I from dbo.Book";
			psmt = Main.con.prepareStatement(sql);
			rs = psmt.executeQuery();
			int count = 0;
			while(rs.next()) { //找到最大的book下标
				count = rs.getInt("I");
			}
			
			sql = "insert into dbo.Book values(?,?,?,?,?,?,?,?,?)";
			psmt = Main.con.prepareStatement(sql);
			psmt.setInt(1, count+1);
			psmt.setString(2, tf_name.getText());
			psmt.setString(3, tf_price.getText());
			psmt.setString(4, tf_auther.getText());
			psmt.setString(5, tf_type.getText());
			psmt.setString(6, tf_des.getText());
			psmt.setBoolean(7, true);
			psmt.setBoolean(8, true);
			psmt.setInt(9, 0);
			psmt.execute();
			JOptionPane.showMessageDialog(null, "插入新书《" + tf_name.getText() +"》成功", "提示", 1);
			quit(null);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "插入新书失败", "提示", 0);
			quit(null);
		}
		
		
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void quit(MouseEvent event) {
		// TODO Autogenerated
		mc.book_Load();
		Main.bookstage.close();
	}
}
