package application.controller;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import application.Main;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.CheckBox;

public class RegisterController {
	@FXML
	private Button btn_Reg;
	@FXML
	private TextField tf_name;
	@FXML
	private TextField tf_password;
	@FXML
	private TextField tf_phone;
	@FXML
	private Button btn_quit;
	@FXML
	private CheckBox cb_accept;
	
	@FXML
	public void initialize() {
		// TODO Autogenerated
		// 设置不能按下
		btn_Reg.setDisable(true);
	}

	// Event Listener on Button[#btn_Reg].onMouseClicked
	@FXML
	public void tryRegister(MouseEvent event) {
		// TODO Autogenerated
		if(tf_name == null || tf_name.getText() == null ) {
			JOptionPane.showMessageDialog(null, "编号不能为空", "提示", 0);
			return;
		}
		if(tf_password == null ||tf_password.getText() == null ) {
			JOptionPane.showMessageDialog(null, "密码不能为空", "提示", 0);
			return;
		}
		else if(tf_password.getText().length() != 8) {
			JOptionPane.showMessageDialog(null, "密码必须为8位", "提示", 0);
			return;
		}
		if(tf_phone == null || tf_phone.getText() == null ) {
			JOptionPane.showMessageDialog(null, "手机号是您找回密码的唯一途径\n不能为空", "提示", 0);
			return;
		}
		String name = tf_name.getText(), password = tf_password.getText();
		String phone = tf_phone.getText(), sql;
		PreparedStatement psmt;
		ResultSet rs;
		try {
			sql = "select count(*) count from dbo.manager";
			psmt = Main.con.prepareStatement(sql);
			rs = psmt.executeQuery();
			int count = 0;
			while (rs.next()) {
				count = rs.getInt("count");
			}
			System.out.println(count);
			
			//转换为string
			String index = Main.addzero(count+1);
			sql = "insert into dbo.Manager values(?,?,?,?)";
			psmt = Main.con.prepareStatement(sql);
			psmt.setString(1, index);
			psmt.setString(2, password);
			psmt.setString(3, name);
			psmt.setString(4, phone);
			psmt.execute();
			JOptionPane.showMessageDialog(null, "注册成功, " + name + " ,您已经成为管理员了\n编号为" + index, "提示", 1);
			quit(null);
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#btn_quit].onMouseClicked
	@FXML
	public void quit(MouseEvent event) {
		// TODO Autogenerated
		Main.regstage.close();
	}
	
	@FXML
	public void accept(MouseEvent event) {
		// TODO Autogenerated
		btn_Reg.setDisable(!cb_accept.isSelected());
	}
	
}
